version: '3'

services:
  postgres:
    image: postgres:13.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "finditdb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "1234"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d finditdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    volumes:      
      - ./postgres-data/postgres:/var/lib/postgresql/data
          
  back_front:
    restart: always
    build: ./src
    ports:
      - "5000:5000"
    volumes:
      - .:/src
    depends_on:
      - postgres
    entrypoint: ["python", "main.py"]

