services:
  postgres:
    image: postgres:13.3
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "finditdb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "1234"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d finditdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G